
arr="amith"
rev=arr[::-1]
print(rev)


# a="ameth"
# vowelscount=0
# conscount=0
# rev=a[::-1]
# print(rev)
# for i in rev:
#   if i=='a' and 'e' and 'i' and 'o' and 'u':
#     vowelscount+=1
#   else:
#     conscount+=1
# print(vowelscount)
# print(conscount)


# a="amith"
# vowelscount=0
# conscount=0
# rev=a[::-1]
# print(rev)

# vowel="ariou"
# for i in rev:
#   if i in vowel:
#     vowelscount+=1
#   else:
#     conscount+=1
# print(vowelscount)
# print(conscount)